# don't build
FROM node:14-slim

COPY ./frontend-content /frontend

RUN apt-get update && apt-get install -y curl

RUN \
    cd /frontend && \
    npm install && \
    npm install --only=dev &&\
    npm install -g @angular/cli > /dev/null

COPY ./frontend-content/src/assets/addons/map-color-theme.css /frontend/node_modules/\@angular/material/prebuilt-themes/
COPY ./frontend-content/src/assets/addons/plotly.js /frontend/node_modules/plotly.js-dist/

HEALTHCHECK       \
    --timeout=3s \ 
    --retries=20  \
    CMD           \
        curl --fail http://localhost:9000 || exit 1
WORKDIR /frontend

CMD ["ng","serve","--host","0.0.0.0","--port","9000", "--disable-host-check"]
